name: Security Checks

on:
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ESLint
        run: npm run lint

      - name: Run Dependency Audit
        run: npm audit --production

      - name: Secrets Scanning
        uses: yannh/kubernetes-gitops@master

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: security
